/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.BorderLayout;

/**
 *
 * @author Leri
 */
public class frContenedor extends javax.swing.JFrame {
    String nombre="";
    /**
     * Creates new form jfContenedor
     */
    public frContenedor() {
        initComponents();
        principal();
    }
    
    private void principal(){
            pnContenedorPrincipal.removeAll();
            pnContenedorPrincipal.repaint();
            pnfPrincipal principal;
            principal = new pnfPrincipal();
            pnContenedorPrincipal.add(principal, BorderLayout.CENTER);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContenedorPrincipal = new javax.swing.JPanel();
        mbMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miPrincipal = new javax.swing.JMenuItem();
        miClientes = new javax.swing.JMenuItem();
        miProveedores = new javax.swing.JMenuItem();
        miMantenimiento = new javax.swing.JMenuItem();
        miMateriales = new javax.swing.JMenuItem();
        miPiezas = new javax.swing.JMenuItem();
        miOrdenes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1150, 700));
        setMinimumSize(new java.awt.Dimension(1150, 700));
        setName("S.G.P.M."); // NOI18N
        setPreferredSize(new java.awt.Dimension(1150, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1150, 700));

        pnContenedorPrincipal.setBackground(new java.awt.Color(102, 153, 255));
        getContentPane().add(pnContenedorPrincipal, java.awt.BorderLayout.CENTER);

        mbMenu.setMaximumSize(new java.awt.Dimension(1150, 40));
        mbMenu.setMinimumSize(new java.awt.Dimension(1150, 40));
        mbMenu.setPreferredSize(new java.awt.Dimension(1150, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N

        miPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        miPrincipal.setText("PAGINA PRINCIPAL");
        miPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPrincipalActionPerformed(evt);
            }
        });
        jMenu1.add(miPrincipal);

        miClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico1.png"))); // NOI18N
        miClientes.setText("NUESTROS CLIENTES");
        miClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(miClientes);

        miProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico2.png"))); // NOI18N
        miProveedores.setText("PROVEEDORES");
        jMenu1.add(miProveedores);

        miMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico3.png"))); // NOI18N
        miMantenimiento.setText("R. DE MANTENIMIENTO");
        miMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(miMantenimiento);

        miMateriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico4.png"))); // NOI18N
        miMateriales.setText("I. DE MATERIALES");
        miMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(miMateriales);

        miPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico5.png"))); // NOI18N
        miPiezas.setText("PIEZAS PARA FABRICACIÓN");
        miPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(miPiezas);

        miOrdenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico6.png"))); // NOI18N
        miOrdenes.setText("ORDENES DE COMPRA");
        miOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(miOrdenes);

        mbMenu.add(jMenu1);

        setJMenuBar(mbMenu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPrincipalActionPerformed

        pnfPrincipal principal = new pnfPrincipal();
        principal.setSize(1100, 600);
        principal.locate(5, 5);
        principal.setVisible(true);

        pnContenedorPrincipal.removeAll();
        pnContenedorPrincipal.add(principal, BorderLayout.CENTER);
        pnContenedorPrincipal.revalidate();
        pnContenedorPrincipal.repaint();
    }//GEN-LAST:event_miPrincipalActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        pnfClientes clientes = new pnfClientes();
        
        clientes.setSize(1100, 600);
        clientes.locate(5, 5);
        clientes.setVisible(true);

        pnContenedorPrincipal.removeAll();
        pnContenedorPrincipal.add(clientes, BorderLayout.CENTER);
        pnContenedorPrincipal.revalidate();
        pnContenedorPrincipal.repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        pnfMantenimientos mantenimientos = new pnfMantenimientos();
        
        mantenimientos.setSize(1100, 600);
        mantenimientos.locate(5, 5);
        mantenimientos.setVisible(true);

        pnContenedorPrincipal.removeAll();
        pnContenedorPrincipal.add(mantenimientos, BorderLayout.CENTER);
        pnContenedorPrincipal.revalidate();
        pnContenedorPrincipal.repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        pnfMateriales materiales = new pnfMateriales();
        
        materiales.setSize(1100, 600);
        materiales.locate(5, 5);
        materiales.setVisible(true);

        pnContenedorPrincipal.removeAll();
        pnContenedorPrincipal.add(materiales, BorderLayout.CENTER);
        pnContenedorPrincipal.revalidate();
        pnContenedorPrincipal.repaint();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        pnfPiezas piezas = new pnfPiezas();
        
        piezas.setSize(1100, 600);
        piezas.locate(5, 5);
        piezas.setVisible(true);

        pnContenedorPrincipal.removeAll();
        pnContenedorPrincipal.add(piezas, BorderLayout.CENTER);
        pnContenedorPrincipal.revalidate();
        pnContenedorPrincipal.repaint();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        pnfOrdenCompra ordenesCompra = new pnfOrdenCompra();
        
        ordenesCompra.setSize(1100, 600);
        ordenesCompra.locate(5, 5);
        ordenesCompra.setVisible(true);

        pnContenedorPrincipal.removeAll();
        pnContenedorPrincipal.add(ordenesCompra, BorderLayout.CENTER);
        pnContenedorPrincipal.revalidate();
        pnContenedorPrincipal.repaint();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frContenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JMenuItem miClientes;
    private javax.swing.JMenuItem miMantenimiento;
    private javax.swing.JMenuItem miMateriales;
    private javax.swing.JMenuItem miOrdenes;
    private javax.swing.JMenuItem miPiezas;
    private javax.swing.JMenuItem miPrincipal;
    private javax.swing.JMenuItem miProveedores;
    private javax.swing.JPanel pnContenedorPrincipal;
    // End of variables declaration//GEN-END:variables
}
