/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Leri
 */
public class frLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public frLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnContenedorPrincipalLog = new javax.swing.JPanel();
        edtUsuarioLog = new javax.swing.JTextField();
        edtPasswordLog = new javax.swing.JPasswordField();
        btnIniciarLog = new javax.swing.JButton();
        eTit1 = new javax.swing.JLabel();
        eTit2 = new javax.swing.JLabel();
        imgSigIn = new javax.swing.JLabel();
        pnPanelColorLog = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesion");
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        pnContenedorPrincipalLog.setBackground(new java.awt.Color(255, 255, 255));
        pnContenedorPrincipalLog.setLayout(null);

        edtUsuarioLog.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        edtUsuarioLog.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnContenedorPrincipalLog.add(edtUsuarioLog);
        edtUsuarioLog.setBounds(20, 260, 350, 27);

        edtPasswordLog.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        edtPasswordLog.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnContenedorPrincipalLog.add(edtPasswordLog);
        edtPasswordLog.setBounds(20, 380, 350, 27);

        btnIniciarLog.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnIniciarLog.setText("Iniciar");
        pnContenedorPrincipalLog.add(btnIniciarLog);
        btnIniciarLog.setBounds(70, 470, 250, 30);

        eTit1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        eTit1.setText("Usuario");
        pnContenedorPrincipalLog.add(eTit1);
        eTit1.setBounds(20, 230, 90, 21);

        eTit2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        eTit2.setText("Contraseña");
        pnContenedorPrincipalLog.add(eTit2);
        eTit2.setBounds(20, 350, 120, 21);

        imgSigIn.setBackground(new java.awt.Color(153, 153, 255));
        imgSigIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SigIn.png"))); // NOI18N
        pnContenedorPrincipalLog.add(imgSigIn);
        imgSigIn.setBounds(130, 50, 128, 130);

        pnPanelColorLog.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout pnPanelColorLogLayout = new javax.swing.GroupLayout(pnPanelColorLog);
        pnPanelColorLog.setLayout(pnPanelColorLogLayout);
        pnPanelColorLogLayout.setHorizontalGroup(
            pnPanelColorLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnPanelColorLogLayout.setVerticalGroup(
            pnPanelColorLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnContenedorPrincipalLog.add(pnPanelColorLog);
        pnPanelColorLog.setBounds(0, 0, 400, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContenedorPrincipalLog, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnContenedorPrincipalLog, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarLog;
    private javax.swing.JLabel eTit1;
    private javax.swing.JLabel eTit2;
    private javax.swing.JPasswordField edtPasswordLog;
    private javax.swing.JTextField edtUsuarioLog;
    private javax.swing.JLabel imgSigIn;
    private javax.swing.JPanel pnContenedorPrincipalLog;
    private javax.swing.JPanel pnPanelColorLog;
    // End of variables declaration//GEN-END:variables
}
