/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import VistaTablas.Vistas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leri
 */
public class pnfClientes extends javax.swing.JPanel {

    /**
     * Creates new form jpClienes
     */
    public pnfClientes() {
        initComponents();
        Tabla();
    }

    public void Tabla(){
        Vistas dis=new Vistas();
        DefaultTableModel modelo=new DefaultTableModel();
        modelo=dis.ModeloCliPro("clientes");
        tbConsultaCli.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoCliente = new javax.swing.ButtonGroup();
        tabClienteCli = new javax.swing.JTabbedPane();
        pnRegistroCli = new javax.swing.JPanel();
        eTit1 = new javax.swing.JLabel();
        edtNomEmpresaCli = new javax.swing.JTextField();
        eTit2 = new javax.swing.JLabel();
        edtDireccionCli = new javax.swing.JTextField();
        eTit3 = new javax.swing.JLabel();
        edtLadaCli = new javax.swing.JTextField();
        edtTelefonoCli = new javax.swing.JTextField();
        eTit4 = new javax.swing.JLabel();
        edtCorreoCli = new javax.swing.JTextField();
        cmbDominiosCli = new javax.swing.JComboBox<>();
        edtOtroDominioCli = new javax.swing.JTextField();
        imgBussisnesman = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        btnLimpiarRegistroCli = new javax.swing.JButton();
        btnGuardarRegistroCli = new javax.swing.JButton();
        eTit5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lbFolioCli = new javax.swing.JLabel();
        eTit13 = new javax.swing.JLabel();
        edtRfcCli = new javax.swing.JTextField();
        pnConsultaCli = new javax.swing.JPanel();
        scp1 = new javax.swing.JScrollPane();
        tbConsultaCli = new javax.swing.JTable();
        eTit6 = new javax.swing.JLabel();
        sep2 = new javax.swing.JSeparator();
        btnBuscarCli = new javax.swing.JButton();
        edtRfcBusquedaCli = new javax.swing.JTextField();
        sep3 = new javax.swing.JSeparator();
        edtNombreEncontradoCli = new javax.swing.JTextField();
        eTit12 = new javax.swing.JLabel();
        lbFolioEncontradoCli = new javax.swing.JLabel();
        eTit7 = new javax.swing.JLabel();
        edtLadaEncontradoCli = new javax.swing.JTextField();
        eTit8 = new javax.swing.JLabel();
        eTit9 = new javax.swing.JLabel();
        edtDireccionEncontradoCli = new javax.swing.JTextField();
        edtTelefonoEncontradoCli = new javax.swing.JTextField();
        edtRfcEncontradoCli = new javax.swing.JTextField();
        eTit10 = new javax.swing.JLabel();
        edtCorreoEncontradoCli = new javax.swing.JTextField();
        eTit11 = new javax.swing.JLabel();
        cmbDominioEncontradoCli = new javax.swing.JComboBox<>();
        edtOtroDomEncontradoCli = new javax.swing.JTextField();
        btnLimpiarConsultaCli = new javax.swing.JButton();
        btnAceptarCli = new javax.swing.JButton();
        rbEliminarCli = new javax.swing.JRadioButton();
        rbModificarCli = new javax.swing.JRadioButton();
        imgTransparenteCli = new javax.swing.JLabel();
        eTit100 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setLayout(null);

        tabClienteCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        pnRegistroCli.setBackground(new java.awt.Color(255, 255, 255));
        pnRegistroCli.setLayout(null);

        eTit1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit1.setText("Nombre de la empresa");
        pnRegistroCli.add(eTit1);
        eTit1.setBounds(20, 40, 150, 18);

        edtNomEmpresaCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnRegistroCli.add(edtNomEmpresaCli);
        edtNomEmpresaCli.setBounds(20, 70, 780, 30);

        eTit2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit2.setText("Direccion");
        pnRegistroCli.add(eTit2);
        eTit2.setBounds(20, 120, 140, 18);

        edtDireccionCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        edtDireccionCli.setToolTipText("");
        pnRegistroCli.add(edtDireccionCli);
        edtDireccionCli.setBounds(20, 150, 780, 30);

        eTit3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit3.setText("Numero telefonico con clave lada");
        pnRegistroCli.add(eTit3);
        eTit3.setBounds(20, 230, 220, 18);

        edtLadaCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnRegistroCli.add(edtLadaCli);
        edtLadaCli.setBounds(20, 260, 100, 30);

        edtTelefonoCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnRegistroCli.add(edtTelefonoCli);
        edtTelefonoCli.setBounds(140, 260, 300, 30);

        eTit4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit4.setText("Correo electronico");
        pnRegistroCli.add(eTit4);
        eTit4.setBounds(20, 310, 150, 18);

        edtCorreoCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnRegistroCli.add(edtCorreoCli);
        edtCorreoCli.setBounds(20, 340, 300, 30);

        cmbDominiosCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbDominiosCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@hotmail.com", "@hotmail.es", "@outlook.com", "@live.com", "@yahoo.com" }));
        pnRegistroCli.add(cmbDominiosCli);
        cmbDominiosCli.setBounds(330, 340, 230, 30);

        edtOtroDominioCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnRegistroCli.add(edtOtroDominioCli);
        edtOtroDominioCli.setBounds(570, 340, 230, 30);

        imgBussisnesman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BusinessMan.png"))); // NOI18N
        imgBussisnesman.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        pnRegistroCli.add(imgBussisnesman);
        imgBussisnesman.setBounds(830, 20, 250, 280);
        pnRegistroCli.add(sep1);
        sep1.setBounds(10, 210, 810, 10);

        btnLimpiarRegistroCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnLimpiarRegistroCli.setText(" Limpiar campos");
        pnRegistroCli.add(btnLimpiarRegistroCli);
        btnLimpiarRegistroCli.setBounds(830, 420, 140, 27);

        btnGuardarRegistroCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnGuardarRegistroCli.setText("Guardar");
        pnRegistroCli.add(btnGuardarRegistroCli);
        btnGuardarRegistroCli.setBounds(980, 420, 100, 27);

        eTit5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        eTit5.setText("Folio:");
        pnRegistroCli.add(eTit5);
        eTit5.setBounds(830, 314, 70, 20);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        pnRegistroCli.add(jSeparator4);
        jSeparator4.setBounds(890, 335, 140, 10);

        lbFolioCli.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lbFolioCli.setOpaque(true);
        pnRegistroCli.add(lbFolioCli);
        lbFolioCli.setBounds(900, 314, 130, 20);

        eTit13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit13.setText("R.F.C.");
        pnRegistroCli.add(eTit13);
        eTit13.setBounds(460, 230, 50, 18);

        edtRfcCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnRegistroCli.add(edtRfcCli);
        edtRfcCli.setBounds(460, 260, 340, 30);

        tabClienteCli.addTab("Registro de Clientes", pnRegistroCli);

        pnConsultaCli.setBackground(new java.awt.Color(255, 255, 255));
        pnConsultaCli.setLayout(null);

        tbConsultaCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scp1.setViewportView(tbConsultaCli);

        pnConsultaCli.add(scp1);
        scp1.setBounds(10, 12, 1070, 90);

        eTit6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit6.setText("R.F.C");
        pnConsultaCli.add(eTit6);
        eTit6.setBounds(10, 120, 34, 14);
        pnConsultaCli.add(sep2);
        sep2.setBounds(10, 110, 1070, 10);

        btnBuscarCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnBuscarCli.setText("Buscar");
        pnConsultaCli.add(btnBuscarCli);
        btnBuscarCli.setBounds(10, 140, 90, 30);
        pnConsultaCli.add(edtRfcBusquedaCli);
        edtRfcBusquedaCli.setBounds(120, 140, 200, 30);
        pnConsultaCli.add(sep3);
        sep3.setBounds(10, 180, 1070, 2);

        edtNombreEncontradoCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnConsultaCli.add(edtNombreEncontradoCli);
        edtNombreEncontradoCli.setBounds(20, 240, 430, 30);

        eTit12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit12.setText("Folio");
        pnConsultaCli.add(eTit12);
        eTit12.setBounds(980, 190, 34, 14);

        lbFolioEncontradoCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbFolioEncontradoCli.setText("__");
        pnConsultaCli.add(lbFolioEncontradoCli);
        lbFolioEncontradoCli.setBounds(1020, 190, 14, 18);

        eTit7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit7.setText("Nombre");
        pnConsultaCli.add(eTit7);
        eTit7.setBounds(20, 220, 60, 18);
        pnConsultaCli.add(edtLadaEncontradoCli);
        edtLadaEncontradoCli.setBounds(510, 240, 80, 30);

        eTit8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit8.setText("Numero Telefonico con clave lada");
        pnConsultaCli.add(eTit8);
        eTit8.setBounds(510, 220, 230, 18);

        eTit9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit9.setText("Direccion");
        pnConsultaCli.add(eTit9);
        eTit9.setBounds(20, 300, 70, 18);

        edtDireccionEncontradoCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnConsultaCli.add(edtDireccionEncontradoCli);
        edtDireccionEncontradoCli.setBounds(20, 320, 430, 30);

        edtTelefonoEncontradoCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnConsultaCli.add(edtTelefonoEncontradoCli);
        edtTelefonoEncontradoCli.setBounds(610, 240, 320, 30);

        edtRfcEncontradoCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnConsultaCli.add(edtRfcEncontradoCli);
        edtRfcEncontradoCli.setBounds(510, 320, 420, 30);

        eTit10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit10.setText("R.F.C.");
        pnConsultaCli.add(eTit10);
        eTit10.setBounds(510, 300, 60, 18);

        edtCorreoEncontradoCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnConsultaCli.add(edtCorreoEncontradoCli);
        edtCorreoEncontradoCli.setBounds(20, 400, 250, 30);

        eTit11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit11.setText("Correo");
        pnConsultaCli.add(eTit11);
        eTit11.setBounds(20, 380, 50, 18);

        cmbDominioEncontradoCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbDominioEncontradoCli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@hotmail.com", "@hotmail.es", "@outlook.com", "@live.com", "@yahoo.com" }));
        pnConsultaCli.add(cmbDominioEncontradoCli);
        cmbDominioEncontradoCli.setBounds(280, 400, 220, 30);

        edtOtroDomEncontradoCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnConsultaCli.add(edtOtroDomEncontradoCli);
        edtOtroDomEncontradoCli.setBounds(510, 400, 240, 30);

        btnLimpiarConsultaCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnLimpiarConsultaCli.setText("Limpiar campos");
        pnConsultaCli.add(btnLimpiarConsultaCli);
        btnLimpiarConsultaCli.setBounds(820, 400, 130, 30);

        btnAceptarCli.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAceptarCli.setText("Aceptar");
        pnConsultaCli.add(btnAceptarCli);
        btnAceptarCli.setBounds(960, 400, 130, 30);

        btnGrupoCliente.add(rbEliminarCli);
        rbEliminarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbEliminarCli.setText("Eliminar");
        rbEliminarCli.setOpaque(false);
        pnConsultaCli.add(rbEliminarCli);
        rbEliminarCli.setBounds(970, 310, 93, 25);

        btnGrupoCliente.add(rbModificarCli);
        rbModificarCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbModificarCli.setSelected(true);
        rbModificarCli.setText("Modificar");
        rbModificarCli.setOpaque(false);
        pnConsultaCli.add(rbModificarCli);
        rbModificarCli.setBounds(970, 260, 90, 25);

        imgTransparenteCli.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(160, 160, 160)));
        pnConsultaCli.add(imgTransparenteCli);
        imgTransparenteCli.setBounds(950, 240, 130, 110);

        tabClienteCli.addTab("Clientes", pnConsultaCli);

        add(tabClienteCli);
        tabClienteCli.setBounds(0, 100, 1100, 500);

        eTit100.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        eTit100.setForeground(new java.awt.Color(255, 255, 255));
        eTit100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eTit100.setText("Nuestros Clientes");
        add(eTit100);
        eTit100.setBounds(280, 14, 550, 90);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarCli;
    private javax.swing.JButton btnBuscarCli;
    private javax.swing.ButtonGroup btnGrupoCliente;
    private javax.swing.JButton btnGuardarRegistroCli;
    private javax.swing.JButton btnLimpiarConsultaCli;
    private javax.swing.JButton btnLimpiarRegistroCli;
    private javax.swing.JComboBox<String> cmbDominioEncontradoCli;
    private javax.swing.JComboBox<String> cmbDominiosCli;
    private javax.swing.JLabel eTit1;
    private javax.swing.JLabel eTit10;
    private javax.swing.JLabel eTit100;
    private javax.swing.JLabel eTit11;
    private javax.swing.JLabel eTit12;
    private javax.swing.JLabel eTit13;
    private javax.swing.JLabel eTit2;
    private javax.swing.JLabel eTit3;
    private javax.swing.JLabel eTit4;
    private javax.swing.JLabel eTit5;
    private javax.swing.JLabel eTit6;
    private javax.swing.JLabel eTit7;
    private javax.swing.JLabel eTit8;
    private javax.swing.JLabel eTit9;
    private javax.swing.JTextField edtCorreoCli;
    private javax.swing.JTextField edtCorreoEncontradoCli;
    private javax.swing.JTextField edtDireccionCli;
    private javax.swing.JTextField edtDireccionEncontradoCli;
    private javax.swing.JTextField edtLadaCli;
    private javax.swing.JTextField edtLadaEncontradoCli;
    private javax.swing.JTextField edtNomEmpresaCli;
    private javax.swing.JTextField edtNombreEncontradoCli;
    private javax.swing.JTextField edtOtroDomEncontradoCli;
    private javax.swing.JTextField edtOtroDominioCli;
    private javax.swing.JTextField edtRfcBusquedaCli;
    private javax.swing.JTextField edtRfcCli;
    private javax.swing.JTextField edtRfcEncontradoCli;
    private javax.swing.JTextField edtTelefonoCli;
    private javax.swing.JTextField edtTelefonoEncontradoCli;
    private javax.swing.JLabel imgBussisnesman;
    private javax.swing.JLabel imgTransparenteCli;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbFolioCli;
    private javax.swing.JLabel lbFolioEncontradoCli;
    private javax.swing.JPanel pnConsultaCli;
    private javax.swing.JPanel pnRegistroCli;
    private javax.swing.JRadioButton rbEliminarCli;
    private javax.swing.JRadioButton rbModificarCli;
    private javax.swing.JScrollPane scp1;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JTabbedPane tabClienteCli;
    private javax.swing.JTable tbConsultaCli;
    // End of variables declaration//GEN-END:variables
}
