/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Leri
 */
public class pnfMateriales extends javax.swing.JPanel {

    /**
     * Creates new form jpMateriales
     */
    public pnfMateriales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMaterialesMat = new javax.swing.JTabbedPane();
        pnRegistroMat = new javax.swing.JPanel();
        eTit1 = new javax.swing.JLabel();
        edtNombreMaterialMat = new javax.swing.JTextField();
        eTit2 = new javax.swing.JLabel();
        cmbTipoMat = new javax.swing.JComboBox<>();
        edtOtroMaterialMat = new javax.swing.JTextField();
        eTit3 = new javax.swing.JLabel();
        cmbMedidaMat = new javax.swing.JComboBox<>();
        eTit4 = new javax.swing.JLabel();
        edtCantidadMat = new javax.swing.JTextField();
        eTit5 = new javax.swing.JLabel();
        cmbUnidadMat = new javax.swing.JComboBox<>();
        eTit6 = new javax.swing.JLabel();
        edtNumeroMat = new javax.swing.JTextField();
        eTit7 = new javax.swing.JLabel();
        scp1 = new javax.swing.JScrollPane();
        txaDescripcionMat = new javax.swing.JTextArea();
        cmbMultiplicadorMat = new javax.swing.JComboBox<>();
        imgBranchEngineering = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        sep2 = new javax.swing.JSeparator();
        btnLimpiarRegistroMat = new javax.swing.JButton();
        btnGuardarRegistroMat = new javax.swing.JButton();
        pnConsultaMat = new javax.swing.JPanel();
        cmbFiltroMat = new javax.swing.JComboBox<>();
        chkFiltrarMat = new javax.swing.JCheckBox();
        scp2 = new javax.swing.JScrollPane();
        tbaConsultaMat = new javax.swing.JTable();
        eTit9 = new javax.swing.JLabel();
        edtNombreEncontradoMat = new javax.swing.JTextField();
        eTit10 = new javax.swing.JLabel();
        cmbTipoEncontradoMat = new javax.swing.JComboBox<>();
        eTit11 = new javax.swing.JLabel();
        cmbMedidaEncontradoMat = new javax.swing.JComboBox<>();
        eTit12 = new javax.swing.JLabel();
        edtCantidadEncontradoMat = new javax.swing.JTextField();
        eTit13 = new javax.swing.JLabel();
        cmbUnidadEncontradoMat = new javax.swing.JComboBox<>();
        cmbMultiplicadorEncontradoMat = new javax.swing.JComboBox<>();
        eTit14 = new javax.swing.JLabel();
        edtNumeroEncontradoMat = new javax.swing.JTextField();
        eTit15 = new javax.swing.JLabel();
        scp3 = new javax.swing.JScrollPane();
        txaDescripcionEncontradoMat = new javax.swing.JTextArea();
        btnBuscarMat = new javax.swing.JButton();
        eTit8 = new javax.swing.JLabel();
        sep3 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        imgTransparenteMat = new javax.swing.JLabel();
        rbEliminarMat = new javax.swing.JRadioButton();
        rbModificarMat = new javax.swing.JRadioButton();
        btnLimpiarConsultaMat = new javax.swing.JButton();
        btnAceptaMat = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 153, 255));
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setLayout(null);

        tabMaterialesMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        tabMaterialesMat.setMaximumSize(new java.awt.Dimension(1100, 600));
        tabMaterialesMat.setMinimumSize(new java.awt.Dimension(1100, 600));

        pnRegistroMat.setBackground(new java.awt.Color(255, 255, 255));
        pnRegistroMat.setLayout(null);

        eTit1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit1.setText("Nombre del material");
        pnRegistroMat.add(eTit1);
        eTit1.setBounds(20, 40, 140, 18);

        edtNombreMaterialMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnRegistroMat.add(edtNombreMaterialMat);
        edtNombreMaterialMat.setBounds(20, 70, 780, 30);

        eTit2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit2.setText("Tipo de material");
        pnRegistroMat.add(eTit2);
        eTit2.setBounds(20, 130, 110, 18);

        cmbTipoMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbTipoMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lamina", "Aluminio", " " }));
        cmbTipoMat.setToolTipText("Describe el genero al que pertenece el nuevo material, por ejemplo un clavo es de la misma categoria que un chilillo.");
        pnRegistroMat.add(cmbTipoMat);
        cmbTipoMat.setBounds(20, 160, 260, 30);

        edtOtroMaterialMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnRegistroMat.add(edtOtroMaterialMat);
        edtOtroMaterialMat.setBounds(310, 160, 270, 30);

        eTit3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit3.setText("Medida");
        pnRegistroMat.add(eTit3);
        eTit3.setBounds(610, 130, 60, 18);

        cmbMedidaMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbMedidaMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Volumen", "Peso", "Pieza" }));
        pnRegistroMat.add(cmbMedidaMat);
        cmbMedidaMat.setBounds(610, 160, 140, 30);

        eTit4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit4.setText("Cantidad");
        pnRegistroMat.add(eTit4);
        eTit4.setBounds(20, 210, 70, 18);

        edtCantidadMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnRegistroMat.add(edtCantidadMat);
        edtCantidadMat.setBounds(20, 240, 150, 30);

        eTit5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit5.setText("Unidad");
        pnRegistroMat.add(eTit5);
        eTit5.setBounds(210, 210, 60, 18);

        cmbUnidadMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbUnidadMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "kg", "mm", "cm", "Mts", "ftp", "inch" }));
        cmbUnidadMat.setToolTipText("Unidad de medida para el material");
        pnRegistroMat.add(cmbUnidadMat);
        cmbUnidadMat.setBounds(200, 240, 80, 30);

        eTit6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit6.setText("Numero de parte");
        pnRegistroMat.add(eTit6);
        eTit6.setBounds(430, 210, 120, 18);

        edtNumeroMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        edtNumeroMat.setToolTipText("");
        pnRegistroMat.add(edtNumeroMat);
        edtNumeroMat.setBounds(430, 240, 110, 30);

        eTit7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit7.setText("Descripcion del material");
        pnRegistroMat.add(eTit7);
        eTit7.setBounds(20, 300, 160, 18);

        txaDescripcionMat.setColumns(20);
        txaDescripcionMat.setRows(5);
        txaDescripcionMat.setToolTipText("Descripcion general del material como medidas, asi mismo si requiere algun cuidado especial, lo puedes agregar en la descripcion.");
        scp1.setViewportView(txaDescripcionMat);

        pnRegistroMat.add(scp1);
        scp1.setBounds(20, 330, 780, 120);

        cmbMultiplicadorMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbMultiplicadorMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cuadrado", "cubica" }));
        pnRegistroMat.add(cmbMultiplicadorMat);
        cmbMultiplicadorMat.setBounds(310, 240, 90, 30);

        imgBranchEngineering.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Branch-Engineering.png"))); // NOI18N
        imgBranchEngineering.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        pnRegistroMat.add(imgBranchEngineering);
        imgBranchEngineering.setBounds(830, 20, 250, 280);
        pnRegistroMat.add(sep1);
        sep1.setBounds(10, 110, 800, 10);
        pnRegistroMat.add(sep2);
        sep2.setBounds(10, 280, 800, 10);

        btnLimpiarRegistroMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnLimpiarRegistroMat.setText(" Limpiar campos");
        pnRegistroMat.add(btnLimpiarRegistroMat);
        btnLimpiarRegistroMat.setBounds(830, 420, 140, 27);

        btnGuardarRegistroMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnGuardarRegistroMat.setText("Guardar");
        pnRegistroMat.add(btnGuardarRegistroMat);
        btnGuardarRegistroMat.setBounds(980, 420, 100, 27);

        tabMaterialesMat.addTab("Registro de materiales nuevos", pnRegistroMat);

        pnConsultaMat.setBackground(new java.awt.Color(255, 255, 255));
        pnConsultaMat.setLayout(null);

        cmbFiltroMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbFiltroMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnConsultaMat.add(cmbFiltroMat);
        cmbFiltroMat.setBounds(110, 10, 260, 30);

        chkFiltrarMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        chkFiltrarMat.setText("Filtrar");
        chkFiltrarMat.setOpaque(false);
        pnConsultaMat.add(chkFiltrarMat);
        chkFiltrarMat.setBounds(20, 10, 63, 30);

        tbaConsultaMat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scp2.setViewportView(tbaConsultaMat);

        pnConsultaMat.add(scp2);
        scp2.setBounds(20, 50, 1060, 90);

        eTit9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit9.setText("Nombre del material");
        pnConsultaMat.add(eTit9);
        eTit9.setBounds(20, 220, 150, 18);
        pnConsultaMat.add(edtNombreEncontradoMat);
        edtNombreEncontradoMat.setBounds(20, 240, 380, 30);

        eTit10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit10.setText("Tipo de material");
        pnConsultaMat.add(eTit10);
        eTit10.setBounds(430, 220, 120, 18);

        cmbTipoEncontradoMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbTipoEncontradoMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnConsultaMat.add(cmbTipoEncontradoMat);
        cmbTipoEncontradoMat.setBounds(430, 240, 180, 30);

        eTit11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit11.setText("Medida");
        pnConsultaMat.add(eTit11);
        eTit11.setBounds(20, 290, 60, 18);

        cmbMedidaEncontradoMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbMedidaEncontradoMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnConsultaMat.add(cmbMedidaEncontradoMat);
        cmbMedidaEncontradoMat.setBounds(20, 310, 180, 30);

        eTit12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit12.setText("Cantidad");
        pnConsultaMat.add(eTit12);
        eTit12.setBounds(230, 290, 70, 18);

        edtCantidadEncontradoMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnConsultaMat.add(edtCantidadEncontradoMat);
        edtCantidadEncontradoMat.setBounds(230, 310, 140, 30);

        eTit13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit13.setText("Unidad");
        pnConsultaMat.add(eTit13);
        eTit13.setBounds(400, 290, 60, 18);

        cmbUnidadEncontradoMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbUnidadEncontradoMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnConsultaMat.add(cmbUnidadEncontradoMat);
        cmbUnidadEncontradoMat.setBounds(400, 310, 100, 30);

        cmbMultiplicadorEncontradoMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbMultiplicadorEncontradoMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuadrado", "Cubico" }));
        pnConsultaMat.add(cmbMultiplicadorEncontradoMat);
        cmbMultiplicadorEncontradoMat.setBounds(510, 310, 100, 30);

        eTit14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit14.setText("Numero de parte");
        pnConsultaMat.add(eTit14);
        eTit14.setBounds(640, 290, 120, 18);

        edtNumeroEncontradoMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnConsultaMat.add(edtNumeroEncontradoMat);
        edtNumeroEncontradoMat.setBounds(640, 310, 200, 30);

        eTit15.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit15.setText("Descripcion");
        pnConsultaMat.add(eTit15);
        eTit15.setBounds(20, 350, 90, 18);

        txaDescripcionEncontradoMat.setColumns(20);
        txaDescripcionEncontradoMat.setRows(5);
        scp3.setViewportView(txaDescripcionEncontradoMat);

        pnConsultaMat.add(scp3);
        scp3.setBounds(20, 376, 610, 60);

        btnBuscarMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnBuscarMat.setText("Buscar");
        pnConsultaMat.add(btnBuscarMat);
        btnBuscarMat.setBounds(20, 170, 90, 30);

        eTit8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit8.setText("Numero de parte");
        pnConsultaMat.add(eTit8);
        eTit8.setBounds(20, 148, 130, 20);
        pnConsultaMat.add(sep3);
        sep3.setBounds(10, 210, 1070, 2);

        jTextField9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        pnConsultaMat.add(jTextField9);
        jTextField9.setBounds(130, 170, 300, 30);

        imgTransparenteMat.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(160, 160, 160)));
        pnConsultaMat.add(imgTransparenteMat);
        imgTransparenteMat.setBounds(920, 240, 130, 110);

        rbEliminarMat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbEliminarMat.setText("Eliminar");
        rbEliminarMat.setOpaque(false);
        pnConsultaMat.add(rbEliminarMat);
        rbEliminarMat.setBounds(940, 310, 93, 25);

        rbModificarMat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbModificarMat.setSelected(true);
        rbModificarMat.setText("Modificar");
        rbModificarMat.setOpaque(false);
        pnConsultaMat.add(rbModificarMat);
        rbModificarMat.setBounds(940, 260, 90, 25);

        btnLimpiarConsultaMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnLimpiarConsultaMat.setText("Limpiar campos");
        pnConsultaMat.add(btnLimpiarConsultaMat);
        btnLimpiarConsultaMat.setBounds(810, 400, 130, 30);

        btnAceptaMat.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAceptaMat.setText("Aceptar");
        pnConsultaMat.add(btnAceptaMat);
        btnAceptaMat.setBounds(950, 400, 130, 30);

        tabMaterialesMat.addTab("Inventario de materiales", pnConsultaMat);

        add(tabMaterialesMat);
        tabMaterialesMat.setBounds(0, 100, 1100, 500);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptaMat;
    private javax.swing.JButton btnBuscarMat;
    private javax.swing.JButton btnGuardarRegistroMat;
    private javax.swing.JButton btnLimpiarConsultaMat;
    private javax.swing.JButton btnLimpiarRegistroMat;
    private javax.swing.JCheckBox chkFiltrarMat;
    private javax.swing.JComboBox<String> cmbFiltroMat;
    private javax.swing.JComboBox<String> cmbMedidaEncontradoMat;
    private javax.swing.JComboBox<String> cmbMedidaMat;
    private javax.swing.JComboBox<String> cmbMultiplicadorEncontradoMat;
    private javax.swing.JComboBox<String> cmbMultiplicadorMat;
    private javax.swing.JComboBox<String> cmbTipoEncontradoMat;
    private javax.swing.JComboBox<String> cmbTipoMat;
    private javax.swing.JComboBox<String> cmbUnidadEncontradoMat;
    private javax.swing.JComboBox<String> cmbUnidadMat;
    private javax.swing.JLabel eTit1;
    private javax.swing.JLabel eTit10;
    private javax.swing.JLabel eTit11;
    private javax.swing.JLabel eTit12;
    private javax.swing.JLabel eTit13;
    private javax.swing.JLabel eTit14;
    private javax.swing.JLabel eTit15;
    private javax.swing.JLabel eTit2;
    private javax.swing.JLabel eTit3;
    private javax.swing.JLabel eTit4;
    private javax.swing.JLabel eTit5;
    private javax.swing.JLabel eTit6;
    private javax.swing.JLabel eTit7;
    private javax.swing.JLabel eTit8;
    private javax.swing.JLabel eTit9;
    private javax.swing.JTextField edtCantidadEncontradoMat;
    private javax.swing.JTextField edtCantidadMat;
    private javax.swing.JTextField edtNombreEncontradoMat;
    private javax.swing.JTextField edtNombreMaterialMat;
    private javax.swing.JTextField edtNumeroEncontradoMat;
    private javax.swing.JTextField edtNumeroMat;
    private javax.swing.JTextField edtOtroMaterialMat;
    private javax.swing.JLabel imgBranchEngineering;
    private javax.swing.JLabel imgTransparenteMat;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pnConsultaMat;
    private javax.swing.JPanel pnRegistroMat;
    private javax.swing.JRadioButton rbEliminarMat;
    private javax.swing.JRadioButton rbModificarMat;
    private javax.swing.JScrollPane scp1;
    private javax.swing.JScrollPane scp2;
    private javax.swing.JScrollPane scp3;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JTabbedPane tabMaterialesMat;
    private javax.swing.JTable tbaConsultaMat;
    private javax.swing.JTextArea txaDescripcionEncontradoMat;
    private javax.swing.JTextArea txaDescripcionMat;
    // End of variables declaration//GEN-END:variables
}
