/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Leri
 */
public class pnfOrdenCompra extends javax.swing.JPanel {

    /**
     * Creates new form jpClienes
     */
    public pnfOrdenCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoCliente = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        eTit1 = new javax.swing.JLabel();
        edtRfcClienteOC = new javax.swing.JTextField();
        btnBuscarClienteOC = new javax.swing.JButton();
        edtNombreEmpresaOC = new javax.swing.JTextField();
        sep1 = new javax.swing.JSeparator();
        cmbDiaOC = new javax.swing.JComboBox<>();
        cmbMesOC = new javax.swing.JComboBox<>();
        cmbAnioOC = new javax.swing.JComboBox<>();
        eTit2 = new javax.swing.JLabel();
        cmbTipoMaterial = new javax.swing.JComboBox<>();
        eTit3 = new javax.swing.JLabel();
        cmbUnidadOC = new javax.swing.JComboBox<>();
        eTit4 = new javax.swing.JLabel();
        edtCantidadOC = new javax.swing.JTextField();
        eTit5 = new javax.swing.JLabel();
        btnAgregarOC = new javax.swing.JButton();
        scp1 = new javax.swing.JScrollPane();
        tbListaPiezasOC = new javax.swing.JTable();
        eTit6 = new javax.swing.JLabel();
        eTit7 = new javax.swing.JLabel();
        eTit8 = new javax.swing.JLabel();
        edtSubTotalOC = new javax.swing.JTextField();
        edtIvaOC = new javax.swing.JTextField();
        edtTotalOC = new javax.swing.JTextField();
        imgSheet = new javax.swing.JLabel();
        btnLimpiarRegistroOC = new javax.swing.JButton();
        btnGuardarRegistroOC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        eTit9 = new javax.swing.JLabel();
        sep2 = new javax.swing.JSeparator();
        btnBuscarOC = new javax.swing.JButton();
        edtRfcBuscarOC = new javax.swing.JTextField();
        eTit15 = new javax.swing.JLabel();
        lbFolioEncontradoOC = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        imgTransparenteOC = new javax.swing.JLabel();
        eTit10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setLayout(null);

        jTabbedPane2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        eTit1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit1.setText("R.F.C. de la empresa cliente");
        jPanel3.add(eTit1);
        eTit1.setBounds(20, 40, 190, 18);

        edtRfcClienteOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(edtRfcClienteOC);
        edtRfcClienteOC.setBounds(20, 70, 470, 30);

        btnBuscarClienteOC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarClienteOC.setText("Buscar");
        jPanel3.add(btnBuscarClienteOC);
        btnBuscarClienteOC.setBounds(510, 70, 90, 30);

        edtNombreEmpresaOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(edtNombreEmpresaOC);
        edtNombreEmpresaOC.setBounds(20, 120, 780, 30);
        jPanel3.add(sep1);
        sep1.setBounds(10, 160, 810, 10);

        cmbDiaOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbDiaOC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dd" }));
        cmbDiaOC.setToolTipText("Dia");
        jPanel3.add(cmbDiaOC);
        cmbDiaOC.setBounds(20, 200, 50, 30);

        cmbMesOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbMesOC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mm" }));
        cmbMesOC.setToolTipText("Mes");
        jPanel3.add(cmbMesOC);
        cmbMesOC.setBounds(80, 200, 60, 30);

        cmbAnioOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbAnioOC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aaaa" }));
        cmbAnioOC.setToolTipText("Año");
        jPanel3.add(cmbAnioOC);
        cmbAnioOC.setBounds(150, 200, 80, 30);

        eTit2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit2.setText("Fecha de entrega");
        jPanel3.add(eTit2);
        eTit2.setBounds(20, 170, 220, 18);

        cmbTipoMaterial.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbTipoMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lamina", "Aluminio", " " }));
        cmbTipoMaterial.setToolTipText("Describe el genero al que pertenece el nuevo material, por ejemplo un clavo es de la misma categoria que un chilillo.");
        jPanel3.add(cmbTipoMaterial);
        cmbTipoMaterial.setBounds(260, 200, 260, 30);

        eTit3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit3.setText("Pieza");
        jPanel3.add(eTit3);
        eTit3.setBounds(260, 170, 110, 18);

        cmbUnidadOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        cmbUnidadOC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "g", "kg", "mm", "cm", "Mts", "ftp", "inch" }));
        cmbUnidadOC.setToolTipText("Unidad de medida para el material");
        jPanel3.add(cmbUnidadOC);
        cmbUnidadOC.setBounds(550, 200, 80, 30);

        eTit4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit4.setText("Unidad");
        jPanel3.add(eTit4);
        eTit4.setBounds(550, 170, 60, 18);

        edtCantidadOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(edtCantidadOC);
        edtCantidadOC.setBounds(660, 200, 60, 30);

        eTit5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit5.setText("Cantidad");
        jPanel3.add(eTit5);
        eTit5.setBounds(660, 170, 60, 18);

        btnAgregarOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAgregarOC.setText("Agregar");
        jPanel3.add(btnAgregarOC);
        btnAgregarOC.setBounds(740, 200, 81, 30);

        tbListaPiezasOC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scp1.setViewportView(tbListaPiezasOC);

        jPanel3.add(scp1);
        scp1.setBounds(20, 240, 800, 130);

        eTit6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit6.setText("Sub total");
        jPanel3.add(eTit6);
        eTit6.setBounds(240, 380, 70, 20);

        eTit7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit7.setText("iva %");
        jPanel3.add(eTit7);
        eTit7.setBounds(370, 380, 30, 18);

        eTit8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit8.setText("Total");
        jPanel3.add(eTit8);
        eTit8.setBounds(510, 380, 32, 18);

        edtSubTotalOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(edtSubTotalOC);
        edtSubTotalOC.setBounds(240, 400, 90, 30);

        edtIvaOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(edtIvaOC);
        edtIvaOC.setBounds(370, 400, 90, 30);

        edtTotalOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(edtTotalOC);
        edtTotalOC.setBounds(510, 400, 90, 30);

        imgSheet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Driller.png"))); // NOI18N
        imgSheet.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel3.add(imgSheet);
        imgSheet.setBounds(830, 20, 250, 280);

        btnLimpiarRegistroOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnLimpiarRegistroOC.setText(" Limpiar campos");
        jPanel3.add(btnLimpiarRegistroOC);
        btnLimpiarRegistroOC.setBounds(830, 420, 140, 27);

        btnGuardarRegistroOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnGuardarRegistroOC.setText("Guardar");
        jPanel3.add(btnGuardarRegistroOC);
        btnGuardarRegistroOC.setBounds(980, 420, 100, 27);

        jTabbedPane2.addTab("Registrar orden de compra", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        eTit9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit9.setText("R.F.C");
        jPanel4.add(eTit9);
        eTit9.setBounds(20, 40, 34, 14);
        jPanel4.add(sep2);
        sep2.setBounds(10, 110, 1070, 10);

        btnBuscarOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnBuscarOC.setText("Buscar");
        jPanel4.add(btnBuscarOC);
        btnBuscarOC.setBounds(20, 60, 90, 30);

        edtRfcBuscarOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel4.add(edtRfcBuscarOC);
        edtRfcBuscarOC.setBounds(130, 60, 480, 30);

        eTit15.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit15.setText("Folio");
        jPanel4.add(eTit15);
        eTit15.setBounds(980, 190, 34, 14);

        lbFolioEncontradoOC.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lbFolioEncontradoOC.setText("__");
        jPanel4.add(lbFolioEncontradoOC);
        lbFolioEncontradoOC.setBounds(1020, 190, 14, 18);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton2.setText("Limpiar campos");
        jPanel4.add(jButton2);
        jButton2.setBounds(820, 400, 130, 30);

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton3.setText("Aceptar");
        jPanel4.add(jButton3);
        jButton3.setBounds(960, 400, 130, 30);

        btnGrupoCliente.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Eliminar");
        jRadioButton1.setOpaque(false);
        jPanel4.add(jRadioButton1);
        jRadioButton1.setBounds(970, 310, 93, 25);

        btnGrupoCliente.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Modificar");
        jRadioButton2.setOpaque(false);
        jPanel4.add(jRadioButton2);
        jRadioButton2.setBounds(970, 260, 90, 25);

        imgTransparenteOC.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(160, 160, 160)));
        jPanel4.add(imgTransparenteOC);
        imgTransparenteOC.setBounds(950, 240, 130, 110);

        eTit10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        eTit10.setText("Informacion de ordenes de compra");
        jPanel4.add(eTit10);
        eTit10.setBounds(20, 130, 230, 18);

        jTabbedPane2.addTab("Ver ordenes de compra", jPanel4);

        add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 100, 1100, 500);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarOC;
    private javax.swing.JButton btnBuscarClienteOC;
    private javax.swing.JButton btnBuscarOC;
    private javax.swing.ButtonGroup btnGrupoCliente;
    private javax.swing.JButton btnGuardarRegistroOC;
    private javax.swing.JButton btnLimpiarRegistroOC;
    private javax.swing.JComboBox<String> cmbAnioOC;
    private javax.swing.JComboBox<String> cmbDiaOC;
    private javax.swing.JComboBox<String> cmbMesOC;
    private javax.swing.JComboBox<String> cmbTipoMaterial;
    private javax.swing.JComboBox<String> cmbUnidadOC;
    private javax.swing.JLabel eTit1;
    private javax.swing.JLabel eTit10;
    private javax.swing.JLabel eTit15;
    private javax.swing.JLabel eTit2;
    private javax.swing.JLabel eTit3;
    private javax.swing.JLabel eTit4;
    private javax.swing.JLabel eTit5;
    private javax.swing.JLabel eTit6;
    private javax.swing.JLabel eTit7;
    private javax.swing.JLabel eTit8;
    private javax.swing.JLabel eTit9;
    private javax.swing.JTextField edtCantidadOC;
    private javax.swing.JTextField edtIvaOC;
    private javax.swing.JTextField edtNombreEmpresaOC;
    private javax.swing.JTextField edtRfcBuscarOC;
    private javax.swing.JTextField edtRfcClienteOC;
    private javax.swing.JTextField edtSubTotalOC;
    private javax.swing.JTextField edtTotalOC;
    private javax.swing.JLabel imgSheet;
    private javax.swing.JLabel imgTransparenteOC;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbFolioEncontradoOC;
    private javax.swing.JScrollPane scp1;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JTable tbListaPiezasOC;
    // End of variables declaration//GEN-END:variables
}
