/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.BorderLayout;

/**
 *
 * @author Leri
 */
public class pnfPrincipal extends javax.swing.JPanel {
    /**
     * Creates new form jpPrincipal
     */
    public pnfPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgPC = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnMateriales = new javax.swing.JButton();
        btnPiezas = new javax.swing.JButton();
        btnOrden = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        eTit1 = new javax.swing.JLabel();
        eTit2 = new javax.swing.JLabel();
        eTit3 = new javax.swing.JLabel();
        eTit4 = new javax.swing.JLabel();
        eTit5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setLayout(null);

        imgPC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PC.png"))); // NOI18N
        add(imgPC);
        imgPC.setBounds(30, 20, 260, 250);

        btnClientes.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnClientes.setText("Nuestros clientes");
        btnClientes.setBorder(null);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        add(btnClientes);
        btnClientes.setBounds(60, 280, 215, 30);

        btnProveedores.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnProveedores.setText("Agenda de proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        add(btnProveedores);
        btnProveedores.setBounds(60, 320, 215, 30);

        btnReportes.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnReportes.setText("Reportes de mantenimiento");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        add(btnReportes);
        btnReportes.setBounds(60, 360, 215, 30);

        btnMateriales.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnMateriales.setText("Inventario de materiales");
        btnMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialesActionPerformed(evt);
            }
        });
        add(btnMateriales);
        btnMateriales.setBounds(60, 400, 215, 30);

        btnPiezas.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnPiezas.setText("Piezas para fabricacion");
        btnPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiezasActionPerformed(evt);
            }
        });
        add(btnPiezas);
        btnPiezas.setBounds(60, 440, 215, 30);

        btnOrden.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnOrden.setText("Ordenes de compra");
        btnOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenActionPerformed(evt);
            }
        });
        add(btnOrden);
        btnOrden.setBounds(60, 480, 215, 30);

        jLabel2.setBackground(new java.awt.Color(255, 0, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico1.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(25, 280, 30, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico2.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(25, 320, 30, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico3.png"))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(25, 360, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico4.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(25, 400, 30, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico5.png"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(25, 440, 30, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ico6.png"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(25, 480, 30, 30);

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        add(jPanel4);
        jPanel4.setBounds(0, 0, 1100, 20);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        add(jPanel2);
        jPanel2.setBounds(300, 0, 3, 600);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        eTit1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        eTit1.setText("Ultimo inicio de sesion");
        jPanel3.add(eTit1);
        eTit1.setBounds(60, 70, 270, 29);

        eTit2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        eTit2.setText("Estado de la base de datos");
        jPanel3.add(eTit2);
        eTit2.setBounds(60, 160, 287, 29);

        eTit3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        eTit3.setText("Ultimo respaldo de la base de datos");
        jPanel3.add(eTit3);
        eTit3.setBounds(60, 260, 400, 29);

        eTit4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        eTit4.setText("Trabajando bajo un iva de");
        jPanel3.add(eTit4);
        eTit4.setBounds(60, 350, 283, 29);

        eTit5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        eTit5.setText("Mantenimientos a maquinaria");
        jPanel3.add(eTit5);
        eTit5.setBounds(60, 450, 320, 29);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Data-Edit.png"))); // NOI18N
        jLabel13.setText("Configuracion ...");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(640, 20, 160, 30);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(jLabel14);
        jLabel14.setBounds(500, 70, 30, 30);

        jLabel15.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(jLabel15);
        jLabel15.setBounds(500, 160, 30, 30);

        jLabel16.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(jLabel16);
        jLabel16.setBounds(500, 450, 30, 30);

        jLabel17.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(jLabel17);
        jLabel17.setBounds(500, 250, 30, 30);

        jLabel18.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.add(jLabel18);
        jLabel18.setBounds(500, 350, 30, 30);

        add(jPanel3);
        jPanel3.setBounds(300, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        this.removeAll();
        pnfClientes cli= new pnfClientes();
        cli.setBounds(0, 0, 1100, 600);
        this.add(cli);
        repaint();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        this.removeAll();
        pnfProveedores pro= new pnfProveedores();
        pro.setBounds(0, 0, 1100, 600);
        this.add(pro);
        repaint();
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        this.removeAll();
        pnfMantenimientos mant= new pnfMantenimientos();
        mant.setBounds(0, 0, 1100, 600);
        this.add(mant);
        repaint();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialesActionPerformed
        this.removeAll();
        pnfMateriales mat= new pnfMateriales();
        mat.setBounds(0, 0, 1100, 600);
        this.add(mat);
        repaint();
    }//GEN-LAST:event_btnMaterialesActionPerformed

    private void btnPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiezasActionPerformed
        this.removeAll();
        pnfPiezas pza= new pnfPiezas();
        pza.setBounds(0, 0, 1100, 600);
        this.add(pza);
        repaint();
    }//GEN-LAST:event_btnPiezasActionPerformed

    private void btnOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenActionPerformed
        this.removeAll();
        pnfOrdenCompra oc= new pnfOrdenCompra();
        oc.setBounds(0, 0, 1100, 600);
        this.add(oc);
        repaint();
    }//GEN-LAST:event_btnOrdenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnMateriales;
    private javax.swing.JButton btnOrden;
    private javax.swing.JButton btnPiezas;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel eTit1;
    private javax.swing.JLabel eTit2;
    private javax.swing.JLabel eTit3;
    private javax.swing.JLabel eTit4;
    private javax.swing.JLabel eTit5;
    private javax.swing.JLabel imgPC;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
