/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Leri
 */
public class pnfProveedores extends javax.swing.JPanel {

    /**
     * Creates new form jpClienes
     */
    public pnfProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoCliente = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField14 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setLayout(null);

        jTabbedPane2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de la empresa");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 40, 150, 18);

        jTextField9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(jTextField9);
        jTextField9.setBounds(20, 70, 780, 30);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setText("Direccion");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 120, 140, 18);

        jTextField10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextField10.setToolTipText("");
        jPanel3.add(jTextField10);
        jTextField10.setBounds(20, 150, 780, 30);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setText("Numero telefonico con clave lada");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 230, 220, 18);

        jTextField11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(jTextField11);
        jTextField11.setBounds(30, 260, 100, 30);

        jTextField12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(jTextField12);
        jTextField12.setBounds(160, 260, 300, 30);

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setText("Correo electronico");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 310, 150, 18);

        jTextField13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(jTextField13);
        jTextField13.setBounds(20, 340, 300, 30);

        jComboBox2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@hotmail.com", "@hotmail.es", "@outlook.com", "@live.com", "@yahoo.com" }));
        jPanel3.add(jComboBox2);
        jComboBox2.setBounds(330, 340, 230, 30);

        jTextField14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(jTextField14);
        jTextField14.setBounds(570, 340, 230, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/House-11.png"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel3.add(jLabel13);
        jLabel13.setBounds(830, 20, 250, 280);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(10, 210, 810, 10);

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton4.setText(" Limpiar campos");
        jPanel3.add(jButton4);
        jButton4.setBounds(830, 420, 140, 27);

        jButton5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton5.setText("Guardar");
        jPanel3.add(jButton5);
        jButton5.setBounds(980, 420, 100, 27);

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel15.setText("Folio:");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(830, 314, 70, 20);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(890, 335, 140, 10);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel16.setOpaque(true);
        jPanel3.add(jLabel16);
        jLabel16.setBounds(900, 314, 130, 20);

        jTabbedPane2.addTab("Registro de proveedores", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 12, 1070, 100);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setText("R.F.C");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 120, 34, 14);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setText("Buscar");
        jPanel4.add(jButton1);
        jButton1.setBounds(10, 140, 73, 30);
        jPanel4.add(jTextField1);
        jTextField1.setBounds(110, 140, 200, 30);
        jPanel4.add(jSeparator2);
        jSeparator2.setBounds(10, 180, 1070, 2);

        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel4.add(jTextField2);
        jTextField2.setBounds(20, 240, 430, 30);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Folio");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(980, 190, 34, 14);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("__");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(1020, 190, 14, 18);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setText("Nombre de la empresa");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(20, 220, 150, 18);
        jPanel4.add(jTextField3);
        jTextField3.setBounds(510, 240, 80, 30);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setText("Numero Telefonico con clave lada");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(510, 218, 230, 20);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setText("Direccion");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 300, 70, 18);

        jTextField4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel4.add(jTextField4);
        jTextField4.setBounds(20, 320, 430, 30);

        jTextField5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel4.add(jTextField5);
        jTextField5.setBounds(610, 240, 320, 30);

        jTextField6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel4.add(jTextField6);
        jTextField6.setBounds(510, 320, 420, 30);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setText("R.F.C.");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(510, 300, 60, 18);

        jTextField7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel4.add(jTextField7);
        jTextField7.setBounds(20, 400, 250, 30);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setText("Correo");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 380, 50, 18);

        jComboBox1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@hotmail.com", "@hotmail.es", "@outlook.com", "@live.com", "@yahoo.com" }));
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(280, 400, 220, 30);

        jTextField8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel4.add(jTextField8);
        jTextField8.setBounds(510, 400, 240, 30);

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton2.setText("Limpiar campos");
        jPanel4.add(jButton2);
        jButton2.setBounds(810, 400, 130, 30);

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton3.setText("Aceptar");
        jPanel4.add(jButton3);
        jButton3.setBounds(950, 400, 130, 30);

        btnGrupoCliente.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton1.setText("Eliminar");
        jRadioButton1.setOpaque(false);
        jPanel4.add(jRadioButton1);
        jRadioButton1.setBounds(970, 310, 93, 25);

        btnGrupoCliente.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Modificar");
        jRadioButton2.setOpaque(false);
        jPanel4.add(jRadioButton2);
        jRadioButton2.setBounds(970, 260, 90, 25);

        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(160, 160, 160)));
        jPanel4.add(jLabel14);
        jLabel14.setBounds(950, 240, 130, 110);

        jTabbedPane2.addTab("Proveedores", jPanel4);

        add(jTabbedPane2);
        jTabbedPane2.setBounds(0, 100, 1100, 500);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
